services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: subscriptions
    ports:
      - "5435:5432"
    volumes:
      - "testtask-pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d subscriptions" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - testtask-net

  migrate:
    image: migrate/migrate:latest
    depends_on:
      db:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:secret@db:5432/subscriptions?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    networks:
      - testtask-net

  app:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - testtask-net

volumes:
  testtask-pgdata:

networks:
  testtask-net:
    driver: bridge
